include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_slow_async_io
    - cancel_subscriptions
    - cascade_invocations
    - use_raw_strings
    - always_use_package_imports
    - avoid_relative_lib_imports
    - use_colored_box
    - use_decorated_box
    - use_is_even_rather_than_modulo
